# For Black pre-commit hook
[tool.black]
line-length = 79

# So isort is compatible with black
[tool.isort]
profile = "black"

# Coverage
[tool.coverage.run]
source = ["surpyval"]

# Flake8
[tool.flake8]
ignore = ['E203', 'W503', 'E741']
per-file-ignores = [
    '*/__init__.py:F401',
]