# For Black pre-commit hook
[tool.black]
line-length = 79

# So isort is compatible with black
[tool.isort]
profile = "black"

# mypy
[tool.mypy]
[[tool.mypy.overrides]]
module = [
    'scipy.*',
    'autograd.*',
    'pandas',
    'numpy_indexed',
    'formulaic',
    'matplotlib.*',
    'autograd_gamma',
    'numba',
    'lifelines',
    'reliability',
    'sphinx_rtd_theme',
    'setuptools',
    'sklearn.*',
    'sksurv.*',
    'joblib.*'
]
ignore_missing_imports = true

# Coverage
[tool.coverage.run]
source = ["surpyval"]

# Flake8
[tool.flake8]
ignore = ['E203', 'W503', 'E741']
per-file-ignores = [
    '*/__init__.py:F401',
]